name: nfc_and_qr_reader
description: Reading NFC tag And QR code
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  nfc_manager:
  package_info:
  provider:
  sqflite:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android.png"
  image_path_ios: "assets/icon/ios.png"
  adaptive_icon_foreground: assets/icon/android_adaptive.png
  adaptive_icon_background: "#4d8cfe"
  remove_alpha_ios: true